# Built-in placeholders:
#
# %date% - The current date.
#
# %displayname% - The player's current display name.
# %gamemode% - The player's current gamemode.
# %health% - The player's current health (rounded).
# %ping% - The player's current ping.
# %username% - The player's username.
# %world% - Current world name.
#
# %maxplayers% - Max player count.
# %players% - Current player count.
# %worldplayers% - The player count of the player's current world.

settings:
  # How should dates in the date placeholder be formatted?
  # Info on formatting: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
  date-format: "MMM dd yyyy"

conditions:
  health:
    true: '&a%health%'
    false: '%condition:health2%'
    criteria:
      - "%health% >= 15"
  health2:
    true: '&e%health%'
    false: '&c%health%'
    criteria:
      - "%health% >= 5"
  checknicked:
    true: 'You are not nicked.'
    false: 'You are currently nicked as %username%.'
    criteria:
      - "%displayname% = %username%"
  checkworld:
    mode: OR
    true: "&aYou are not in the overworld!"
    false: "&aYou are in the overworld!"
    criteria:
      - "%world% -| nether"
      - "%world% -| end"

scoreboards:
  default:
    weight: 10
    trigger: DEFAULT

    title:
      random: false
      speed: 100
      text:
        - "&1This &9is &1the &9default &1scoreboard!"
        - "&9This &1is &9the &1default &9scoreboard!"

    line1:
      left-aligned:
        random: false
        speed: 20
        text:
          - ""
          - "Welcome "
          - "Welcome to "
          - "Welcome to the "
          - "Welcome to the server!"

      right-aligned:
        random: false
        speed: 20
        text:
          - "Welcome to the server!"
          - "to the server!"
          - "the server!"
          - "server!"
          - ""

    line2:
      left-aligned:
        random: false
        speed: 40
        text:
          - '&7Today is %date%.'
          - '&8Today is %date%.'

    line3:
      right-aligned:
        random: false
        speed: 10
        text:
          - '%condition:checkworld%'

  nether:
    weight: 15
    trigger: WORLD_WHITELIST
    worlds:
      - "world_nether"

    title:
      random: false
      speed: 5
      text:
        - "&bThis is the nether scoreboard."

    line1:
      left-aligned:
        random: false
        speed: -1
        text:
          - "&7World | "

      right-aligned:
        random: false
        speed: 10
        text:
          - "&7%world%"

    line2:
      left-aligned:
        random: false
        speed: -1
        text:
          - "&7Ping | "

      right-aligned:
        random: false
        speed: 10
        text:
          - "&7%ping%ms"

    line3:
      left-aligned:
        random: false
        speed: -1
        text:
          - "&7Coordinates | "
      right-aligned:
        random: false
        speed: 10
        text:
          # Placeholder API player placeholders. /papi ecloud download Player
          - '&7%player_x%, %player_y%, %player_z%.'

  permission:
    weight: 12
    trigger: PERMISSION
    permission: "better.scoreboard.permission"

    title:
      random: true
      speed: 100
      text:
        - "&bThis is the permission board!"
        - "&bYou must be OP or have the permission!"

    line1:
      left-aligned:
        random: true
        speed: -1
        text:
          - "&8Your username is %username%."
          - "&8Your gamemode is %gamemode%."

    line2:
      left-aligned:
        random: false
        speed: 10
        text:
          - "&7Your ping is:"
          - "&8Your ping is:"

      right-aligned:
        random: false
        speed: 10
        text:
          - "&7%ping%"
          - "&8%ping%"

    line3:
      left-aligned:
        mode: OR
        criteria:
          - "%world% -| nether"

        random: true
        speed: 10
        text:
          - "This is left aligned nether text!"

      right-aligned:
        random: false
        speed: 20
        text:
          - "This is aligned to the right!"

    line4:
      right-aligned:
        mode: OR
        criteria:
          - "%world% -| nether"
        speed: -1
        text:
          - "This line only shows up in the nether!"

    line5:
      left-aligned:
        speed: -1
        text:
          - "This is the 5th line!"