# Built-in placeholders:
#
# %date% - The current date.
#
# %displayname% - The player's current display name.
# %gamemode% - The player's current gamemode.
# %health% - The player's current health (rounded).
# %ping% - The player's current ping.
# %username% - The player's username.
# %world% - Current world name.
#
# %maxplayers% - Max player count.
# %players% - Current player count.
# %worldplayers% - The player count of the player's current world.

settings:
  # How should dates in the date placeholder be formatted?
  # Info on formatting: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
  date-format: "MMM dd yyyy"

conditions:
  health:
    true: '&7%health%'
    false: '%condition:health2%'
    criteria:
      - "%health% >= 15"
  health2:
    true: '&e%health%'
    false: '%c%health%'
    criteria:
      - "%health% >= 5"
  checknicked:
    true: 'You are not nicked.'
    false: 'You are currently nicked as %username%.'
    criteria:
      - "%displayname% = %username%"
  checkworld:
    mode: OR
    true: "&aYou are not in the overworld!"
    false: "&aYou are in the overworld!"
    criteria:
      - "%world% -| nether"
      - "%world% -| end"

scoreboards:
  default:
    weight: 10
    hide-numbers: true
    trigger: DEFAULT

    title:
      random: false
      animation-speed: 100
      animation:
        - "&1This &9is &1the &9default &1scoreboard!"
        - "&9This &1is &9the &1default &9scoreboard!"

    line1:
      random: false
      animation-speed: 20
      animation:
        - "&7Welcome to the server!"

    line2:
      random: false
      animation-speed: 40
      animation:
        - '&7Today is %date%.'
        - '&8Today is %date%.'

  nether:
    weight: 15
    hide-numbers: false
    trigger: WORLD_WHITELIST
    worlds:
      - "world_nether"

    title:
      random: false
      animation-speed: 5
      animation:
        - "&bThis is the nether scoreboard."

    line1:
      random: false
      animation-speed: 20
      animation:
        - "&7Your world is %world%."

    line2:
      random: false
      animation-speed: 10
      animation:
        - '&7Your ping is %ping%.'

    line3:
      random: false
      animation-speed: 10
      animation:
        # Placeholder API player placeholders. /papi ecloud download Player
        - '&7Your x value is %player_x%.'

  permission:
    weight: 12
    hide-numbers: true
    trigger: PERMISSION
    permission: "better.scoreboard.permission"

    title:
      random: true
      animation-speed: 100
      animation:
        - "&bThis is the permission board!"
        - "&bYou must be OP or have the permission!"

    line1:
      random: true
      animation-speed: -1
      animation:
        - "&8Your username is %username%."
        - "&8Your gamemode is %gamemode%."

    line2:
      random: false
      animation-speed: 10
      animation:
        - "&7Your ping is %ping%."
        - "&8Your ping is %ping%."

    line3:
      random: false
      animation-speed: 20
      animation:
        - '&7Your health is %condition:health%'