name: BetterScoreboard
version: 1.4.0
main: better.scoreboard.BetterScoreboard
api-version: 1.13
load: POSTWORLD
folia-supported: true
softdepend:
  - BetterReload
  - PlaceHolderAPI
depend:
  - packetevents
authors:
  - am noah